from enum import Enum


class EventType(str, Enum):
    NOTE_FACT_ADDED = "NOTE_FACT_ADDED"
    NOTE_CONTRADICTION_CANDIDATE_ADDED = "NOTE_CONTRADICTION_CANDIDATE_ADDED"
    NOTE_CREATED = "NOTE_CREATED"
    NOTE_UPDATED = "NOTE_UPDATED"
    NOTE_DELETED = "NOTE_DELETED"
    EVIDENCE_UNLOCKED = "EVIDENCE_UNLOCKED"
    TIMELINE_EVENT_REVEALED = "TIMELINE_EVENT_REVEALED"
    TENSION_CHANGED = "TENSION_CHANGED"
    VISUAL_STATE_CHANGED = "VISUAL_STATE_CHANGED"
    BOOKMARK_SUGGESTED = "BOOKMARK_SUGGESTED"
    VISUAL_REACTION_SUGGESTED = "VISUAL_REACTION_SUGGESTED"
    DEBUG_SESSION_UPDATED = "DEBUG_SESSION_UPDATED"
    ACCUSATION_RESOLVED = "ACCUSATION_RESOLVED"


SUPPORTED_EVENT_TYPES = {event_type.value for event_type in EventType}
NOTE_EVENT_TYPES = {
    EventType.NOTE_FACT_ADDED.value,
    EventType.NOTE_CONTRADICTION_CANDIDATE_ADDED.value,
}
GAME_MASTER_PUBLIC_EVENT_TYPES = {
    EventType.NOTE_FACT_ADDED.value,
    EventType.NOTE_CONTRADICTION_CANDIDATE_ADDED.value,
    EventType.BOOKMARK_SUGGESTED.value,
}
